version: '3.8'

services:
  dbctrlfinanceito:
    image: mysql
    env_file: ./.env
    container_name: dbctrlfinanceito
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      # TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:      
      - mysql-data:/var/lib/mysql
      - ./docker/db/my.cnf:/etc/my.cnf
      - "./docker/db/sql/setup.sql:/docker-entrypoint-initdb.d/1.sql"
    ports:
      - 3306:3306
    networks:
      - app-connect

  controlefinanceiro.webapi:
    image: ${DOCKER_REGISTRY-}controlefinanceiro
    build:
      context: .
      dockerfile: ControleFinanceiro.WebApi/Dockerfile        
    depends_on:
      - dbctrlfinanceito
    ports:
      - 4002:4200      
    restart: always
    #Specify Environment Variables for the Api Service
    environment: 
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:4200
    #volumes:
    #  - ~/.aspnet/https:/root/.aspnet/https:ro
    #  - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro

volumes:
  mysql-data:
    driver: local

networks:
  app-connect:
      driver: bridge
